name: workflow windows
on: workflow_dispatch
jobs:
  first_job:
    runs-on: windows-latest
    steps:
     - name: Print hello
       run: echo "Hello World Action"
     - name: Print bye
       run: echo "bye bye"
